# Generated by Django 5.2.8 on 2025-11-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='id',
        ),
        migrations.AddField(
            model_name='escuela',
            name='idEscuela',
            field=models.AutoField(db_column='idEscuela', primary_key=True, serialize=False),
        ),
    ]
