# Generated by Django 5.2.8 on 2025-11-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0002_remove_escuela_id_escuela_idescuela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='idEscuela',
        ),
        migrations.AddField(
            model_name='escuela',
            name='idescuela',
            field=models.AutoField(db_column='idescuela', primary_key=True, serialize=False),
        ),
    ]
