# Generated by Django 5.2.8 on 2025-11-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0003_remove_escuela_idescuela_escuela_idescuela'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escuela',
            old_name='idescuela',
            new_name='idEscuela',
        ),
    ]
