# Generated by Django 5.2.8 on 2025-11-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'managed': False},
        ),
    ]
