# Generated by Django 5.2.8 on 2025-11-27 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('uniformes', '0004_varianteuniforme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('notas', models.CharField(blank=True, max_length=200, null=True)),
                ('idCliente', models.ForeignKey(db_column='idcliente', on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idVariante', models.ForeignKey(db_column='idvariante', on_delete=django.db.models.deletion.CASCADE, to='uniformes.varianteuniforme')),
                ('idPedido', models.ForeignKey(db_column='idpedido', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.pedido')),
            ],
            options={
                'db_table': 'detalle_pedidos',
            },
        ),
    ]
