# Generated by Django 5.2.8 on 2025-11-29 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('ventas', '0004_alter_pedido_creado_por'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado'),
        ),
    ]
