# Generated by Django 5.2.8 on 2025-11-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_detallepedido_options_alter_pedido_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='notas',
            field=models.TextField(blank=True, db_column='notas', null=True),
        ),
    ]
