# Generated by Django 5.2.8 on 2025-11-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_pedido_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='abono',
            field=models.DecimalField(db_column='abono', decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='abono',
            new_name='abono_acumulado',
        ),
    ]
