# Generated by Django 5.2.8 on 2025-11-27 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uniforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('idEscuela', models.ForeignKey(db_column='idEscuela', on_delete=django.db.models.deletion.CASCADE, related_name='uniformes', to='escuelas.escuela')),
            ],
            options={
                'db_table': 'uniformes',
            },
        ),
    ]
