# Generated by Django 5.2.8 on 2025-11-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniforme',
            name='id',
        ),
        migrations.AddField(
            model_name='uniforme',
            name='idUniforme',
            field=models.AutoField(db_column='idUniforme', primary_key=True, serialize=False),
        ),
    ]
