# Generated by Django 5.2.8 on 2025-11-27 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0003_remove_escuela_idescuela_escuela_idescuela'),
        ('uniformes', '0002_remove_uniforme_id_uniforme_iduniforme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniforme',
            name='idEscuela',
            field=models.ForeignKey(db_column='idescuela', on_delete=django.db.models.deletion.CASCADE, related_name='uniformes', to='escuelas.escuela'),
        ),
        migrations.AlterField(
            model_name='uniforme',
            name='idUniforme',
            field=models.AutoField(db_column='iduniforme', primary_key=True, serialize=False),
        ),
    ]
