# Generated by Django 5.2.8 on 2025-11-27 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0003_alter_uniforme_idescuela_alter_uniforme_iduniforme'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarianteUniforme',
            fields=[
                ('idVariante', models.AutoField(db_column='idvariante', primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('idUniforme', models.ForeignKey(db_column='iduniforme', on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='uniformes.uniforme')),
            ],
            options={
                'db_table': 'variantes_u',
                'unique_together': {('idUniforme', 'talla')},
            },
        ),
    ]
