# Generated by Django 5.2.8 on 2025-12-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0004_varianteuniforme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniforme',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='varianteuniforme',
            options={'managed': False},
        ),
    ]
