# Generated by Django 5.2.8 on 2025-11-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='idCliente',
            field=models.AutoField(db_column='idcliente', primary_key=True, serialize=False),
        ),
    ]
