# Generated by Django 5.2.8 on 2025-11-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('idCaja', models.AutoField(db_column='idcaja', primary_key=True, serialize=False)),
                ('abierto_en', models.DateTimeField(db_column='abierto_en')),
                ('cerrado_en', models.DateTimeField(blank=True, db_column='cerrado_en', null=True)),
                ('fondo_inicial', models.DecimalField(db_column='fondo_inicial', decimal_places=2, max_digits=10)),
                ('conteo_final', models.DecimalField(blank=True, db_column='conteo_final', decimal_places=2, max_digits=10, null=True)),
                ('dinero_esperado', models.DecimalField(blank=True, db_column='dinero_esperado', decimal_places=2, max_digits=10, null=True)),
                ('diferencia', models.DecimalField(blank=True, db_column='diferencia', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'caja',
                'managed': False,
            },
        ),
    ]
