# Generated by Django 5.2.8 on 2025-12-08 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaMovimiento',
            fields=[
                ('idMovimiento', models.AutoField(db_column='idmovimiento', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada de Dinero'), ('SALIDA', 'Salida de Dinero')], db_column='tipo', max_length=10)),
                ('monto', models.DecimalField(db_column='monto', decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=255)),
                ('fecha', models.DateTimeField(db_column='fecha', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'caja_movimientos',
                'ordering': ['-fecha'],
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='caja',
            table='caja_sesiones',
        ),
    ]
